### ISSUE TITLE
List type slot is filled by the first element of the list only while using FormAction

### ISSUE THREAD

**Issue by palash247** [RasaHQ/rasa_core_sdk#24]
**Python version:** 3.6.5

**Rasa core sdk version:** 0.11.5

**Issue:** I have a list type slot and I am writing a custom FormAction with the same slot being one of the required_field. While performing online training, the list type slot is storing only the first element of the entity list detected by the NLU server while ignoring the others. While going through the code, I found the following line of code being the reason for this behavior:

https://github.com/RasaHQ/rasa_core_sdk/blob/5b2356e2e0f43a95fbc988f66104948c7aed9ae6/rasa_core_sdk/forms.py#L44

This line of code works if the slot type is nonlist. For list type we need something like `value = list(tracker.get_latest_entity_values(self.entity_name))`. I don't know if there is a way to check the type of slot before filling it. If there's, this should be an easy fix.

**Comment by akelad** [comment]
Thanks for noticing this, we're actually merging a new forms version soon so this is outdated code. @Ghostvv this probably applies to our new version too though right?
