### ISSUE TITLE
`RANDOMIZE` has no effect 

### ISSUE THREAD

**Issue by ksurya** [RasaHQ/rasa_core_sdk#26]
https://github.com/RasaHQ/rasa_core_sdk/blob/d5772cd41a00a822422ae5bc4eeb221990379566/rasa_core_sdk/forms.py#L147

If `len(fields)` is expected to be 1, the random shuffle of required fields will have no effect!

**Comment by akelad** [comment]
hey, we're working on a refactor of forms right now (see the open pull request) which should be merged today, so this is no longer relevant
