### ISSUE TITLE
FormAction utterances do not use preceding extracted slots

### ISSUE THREAD

**Issue by tahesse** [RasaHQ/rasa_core_sdk#27]
Hello @RasaHQ,

I've created a running custom `FormAction` that is supposed to extract the `forename` and `surname` to finally submit the extracted slots. I have noticed the following unwanted behavior:

B: Hey there, I'm Rasa Bot.
B: Please tell me your forename.
U: Thomas
B: Alright **None**. Please tell me your surname.
U: Hesse
B: Thanks, **Thomas None**.

So apparently preceding extracted slots are not substituted into the `utter_ask_{SLOT}` utterances which is quite unfortunate as it takes a lot of power from the `FormAction`s. As of now, I was not able to narrow down the source of the problem, though, I was asked ([in the forums](https://forum.rasa.com/t/rasa-core-formaction-cannot-access-slots-in-the-follow-up-utter-ask-slot/2890)) to file this issue. However, I shall point out that the response of the action server seems fine to me! That is, it contains the extracted slots and the next `requested_slot` but (IMO on the rasa-core side) the bot utters before the slot is set.

Looking forward to any help, I'm back debugging. :-)

My Rasa Core Version: **0.12.2** and my `actions.py`:

```
class TestFormAction(FormAction):
    """Example of a custom form action"""

    def name(self):
        # type: () -> Text
        """Unique identifier of the form"""

        return "action_test_form"

    def slot_mappings(self):
        # type: () -> Dict[Text: Union[Text, Dict, List[Text, Dict]]]
        """A dictionary to map required slots to
            - an extracted entity
            - intent: value pairs
            - a whole message
            or a list of them, where the first match will be picked"""

        return {
            'surname': [
                self.from_entity(entity='surname', intent='get_surname'),
                self.from_entity(entity='surname', intent='get_full_name'),
                self.from_text(intent='get_surname'),
            ],
            'forename': [
                self.from_entity(entity='forename'),
                self.from_text(intent='get_forename'),
            ],
        }

    @staticmethod
    def required_slots(tracker):
        # type: (Tracker) -> List[Text]
        """A list of required slots that the form has to fill"""

        return [
            'forename',
            'surname',
        ]

    def submit(self, dispatcher, tracker, domain):
        # type: (CollectingDispatcher, Tracker, Dict[Text, Any]) -> List[Dict]
        """Define what the form has to do
           after all required slots are filled"""

        # utter submit template
        dispatcher.utter_template('utter_data_full_name', tracker)
        return []

```

**Comment by tahesse** [comment]
I dug a bit deeper and **it seems** that the problem really is on the `rasa_core` side. Shall I reopen this issue in the `rasa_core` repo or can someone move it over there?

The line to which I debugged is https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/actions/action.py#L358 in which the events (with the extracted slots) are still not processed while the bot is already on its way to utter the next action from the submit. I'll debug further and get back when I got new insights.

**Comment by tahesse** [comment]
Issue is resolved!
See [this link in the forums for clarification](https://forum.rasa.com/t/rasa-core-formaction-cannot-access-slots-in-the-follow-up-utter-ask-slot/2890/9).

**Comment by Ghostvv** [comment]
the solution described in the forum is about different thing. So, I'll reopen this issue

**Comment by tahesse** [comment]
Thanks @Ghostvv. Your branch `tracker-update-utterance` looks good to me now! Should be ready to merge. :-)
