### ISSUE TITLE
How do I subclass Action without the executor trying to import it?

### ISSUE THREAD

**Issue by m90** [RasaHQ/rasa_core_sdk#29]
I would like to instrument a custom action. To do so, I was thinking I could just do something like this:

```py
class InstrumentedAction(Action):
    pass
    # the code in here is not relevant for the issue
```

and my actions would then look like:

```py
class SomeAction(InstrumentedAction):
    def name(self):
        return "my_name"
    def run(self, dispatcher, tracker, domain):
        pass
```

Interestingly having this class somewhere in my project will throw when calling `register_package` on the Executor. The reason for that is that in my example `InstrumentedAction` will also be included in the list of classes gathered here: https://github.com/RasaHQ/rasa_core_sdk/blob/47106d959767148d15b328a3a38a95cd697e0616/rasa_core_sdk/executor.py#L149-L154 which in turn raises an exception here: https://github.com/RasaHQ/rasa_core_sdk/blob/47106d959767148d15b328a3a38a95cd697e0616/rasa_core_sdk/executor.py#L104-L105 as the instance of `InstrumentedAction` will raise a `NonImplementedError` when calling `name()`

I do know I could hack around this by simply implementing a `name()` on my subclass, but it feels weird to register the class instance in the first place and it's also not very obvious when it comes to debugging.

Can you think of a nicer way of doing this? Could the SDK handle this case in some way or the other?

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by m90** [comment]
Since the approach above currently won't work (and is probably also not the most pythonic anyways), I tried using a class decorator for augmenting the action classes like this:

```py
@add_things_to_action
class ActionLookupThings(Action):
    pass
```

This works fine if I import the action in the REPL, but I am facing another very strange issue when the Executor imports this: for reasons unknown to me rasa will import and instantiate the un-decorated version of the class.

If I `inspect.getsource(action)` in here: 
 https://github.com/RasaHQ/rasa_core_sdk/blob/master/rasa_core_sdk/executor.py#L149 I will see the undecorated class, when I do the same in the REPL, importing the same path, I will see the decorated version.

I would assume the culprit for this is to be found in this method: https://github.com/RasaHQ/rasa_core_sdk/blob/47106d959767148d15b328a3a38a95cd697e0616/rasa_core_sdk/utils.py#L11-L16 but my import fu is too weak to know how to do it better

**Comment by m90** [comment]
This is really tricky. If we wanted to consider decorated versions too the SDK could be doing something like this:

```py
def register_package(self, package):
    try:
        # _import_submodules would return a list
        # it currently never returns `result`
        results = self._import_submodules(package)
    except ImportError:
        logger.exception("Failed to register package '{}'." "".format(package))

    actions = []
    for pkg in results:
        exports = [cls for _, cls in pkg.__dict__.items() if isinstance(cls, type)]
        subclasses = [cls for cls in exports if issubclass(cls, Action)]
        actions += subclasses

    for action in actions:
        if not action.__module__.startswith(
            "rasa_core"
        ) and not action.__module__.startswith("rasa_core_sdk"):
            self.register_action(action)
```

but then I would not know how to do the filtering from #30 as the decorated classes would be coming from a non-package path.

Maybe this is still nicer though?

**Comment by tmbo** [comment]
You lost me there, does your decorator approach work or does it not? 🙂 

I agree with you, the decorator approach is more pythonic and also more explicit about what gets added as an action.

**Comment by m90** [comment]
I got a little lost here too :dizzy: sorry for the confusion.

To sum up what I found out:

- Applying a class decorator to an Action class works for me, yet I found out the following. When looking up all subclasses here: https://github.com/RasaHQ/rasa_core_sdk/blob/bdc7611dd3c4c5e9a932a02a10830f389a3a7b53/rasa_core_sdk/executor.py#L149 both the decorated and the plain class will be returned. As both share the same name, the second one that is being registered will overwrite the first one here: https://github.com/RasaHQ/rasa_core_sdk/blob/bdc7611dd3c4c5e9a932a02a10830f389a3a7b53/rasa_core_sdk/executor.py#L105 In my particular case the decorated ones will come last, so things work as expected, but I do not know enough about the module resolution mechanics behind all this to know if this is expected or just coincidence?
- Even if a decorator is more pythonic, I wonder if a way of excluding Actions from being registered is needed? I could still see people writing intermediate action classes to inherit from and maybe even have things like side effects in their init functions, so just instantiating and registering everything that inherits from Action and does not live in a `rasa_*` package sounds slightly dangerous.

**Comment by m90** [comment]
Another thing I just ran into: I might have integration tests in my repository that have Actions I don't necessarily want to be loaded alongside my production ones.

**Comment by smn-snkl** [comment]
Any update on this? I think sub-classing an Action or FormAction is a pretty standard functionality that should be supported. For example, I have a few FormActions that have a custom validate function. Would be nice if I could just create a CustomFormAction(FormAction) without the CustomFormAction being imported as an Action on startup and raising a NotImplementedError("A form must implement a name")

**Comment by tmbo** [comment]
Well, I agree - we should fix this. The question is how - would need to do some research on pythonic ways to do this. any suggestions other than the annotation?

**Comment by smn-snkl** [comment]
Thinking of adjusting the Action discovery process by adding something to abstract FormActions to identify them as being abstract. For example, I could think of something like Django is using for Abstract Models: [here](https://docs.djangoproject.com/en/2.1/topics/db/models/#abstract-base-classes)

This would also allow for other types of "Action meta configuration" in the future.

So a customized FormAction base class could look like this:
```
class CustomFormActionBase(FormAction):
    class Meta:
        abstract = True

    def validate(...):
         ...
```

And in the `executor` these few lines could be changed from:
https://github.com/RasaHQ/rasa_core_sdk/blob/47106d959767148d15b328a3a38a95cd697e0616/rasa_core_sdk/executor.py#L151-L154

to:
```
for action in actions:
    meta = getattr(CustomAction, 'Meta', False)
    abstract = getattr(meta, 'abstract', False)
    if (not action.__module__.startswith("rasa_core.") and
            not action.__module__.startswith("rasa_core_sdk.")) and
            not abstract:
        self.register_action(action)
```

Just a thought, haven't tested if this would work, but something alike could do the job.

**Comment by smn-snkl** [comment]
Just started testing this in my own fork. Referenced this issue in a non-ready [PR](https://github.com/RasaHQ/rasa_core_sdk/pull/49)

**Comment by tmbo** [comment]
I guess we can close this one :tada:
