### ISSUE TITLE
FormAction is not working

### ISSUE THREAD

**Issue by saqibahmed515** [RasaHQ/rasa_core_sdk#3]
**Rasa Core SDK version**:
0.11.0 . (taken from `pip show rasa_core_sdk`)
**Python version**: 
3.6.5
**Operating system** (windows, osx, ...):
osx
**Issue**:
I'm running `python -m rasa_core_sdk.endpoint --actions actions` where I have a class in my actions which inherits `FormAction` and overrides `required_fields()`, `name()` and `submit()` functions. In my IDE, I can see in the rasa_core_sdk.forms.py that my overriden function for name is being shown, but when I execute endpoint, I get the `NotImplementedError` for `name()` function.  

All the other actions (other than `FormAction`) are working perfectly.

**FormAction**
```python
from rasa_core_sdk.forms import FormAction, EntityFormField
class ActionProvideOfferFillSlots(FormAction):
    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("Firstname", "Firstname"),
            EntityFormField("Email", "Email"),
        ]

    def name(self):
        return 'action_provide_offer_fill_slots'

    def submit(self, dispatcher, tracker, domain):
        ... ... ... ...

```

**Stack trace**
```bash
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/rasa_core_sdk/endpoint.py", line 89, in <module>
    action_package_name=cmdline_args.actions)
  File "/usr/local/lib/python3.6/site-packages/rasa_core_sdk/endpoint.py", line 55, in endpoint_app
    executor.register_package(action_package_name)
  File "/usr/local/lib/python3.6/site-packages/rasa_core_sdk/executor.py", line 153, in register_package
    self.register_action(action)
  File "/usr/local/lib/python3.6/site-packages/rasa_core_sdk/executor.py", line 105, in register_action
    self.register_function(action.name(), action.run)
  File "/usr/local/lib/python3.6/site-packages/rasa_core_sdk/forms.py", line 96, in name
    raise NotImplementedError
NotImplementedError
```

**Comment by saqibahmed515** [comment]
Got it fixed by inheriting the `ActionExecutor` and overriding `register_package` as below:

```python
class CustomExecutor(ActionExecutor):
    def register_package(self, package):
        try:
            self._import_submodules(package)
        except ImportError:
            logger.exception("Failed to register package '{}'."
                             "".format(package))

        actions = utils.all_subclasses(Action)

        for action in actions:
            if not action.__module__.startswith("rasa_core.") and \
               not action.__module__.startswith("rasa_core_sdk."):
                self.register_action(action)
```

**Comment by arachny** [comment]
@saqibahmed515 how did you use the CustomExecutor? I am having the same issues (NotImplementedError) and cannot figure out how to fix that.

**Comment by arachny** [comment]
Yes, I realized eventually. Thanks for the reply.

**Comment by pragya-96** [comment]
my form action is not working.no reply from the end.My bot gets stuck when i ask query regarding can anybody help me with the issue
my action.py file:
from rasa_core.actions import Action
from rasa_core_sdk.events import SlotSet
from rasa_core.actions.action import Action
from rasa_core_sdk.forms import FormAction
from rasa_core_sdk.forms import EntityFormField
class ActionOrderPizza(Action):
    def required_fields():
                return [
                EntityFormField("size", "size"),
                EntityFormField("toppings", "toppings")
                ]
    def name(self):
        return 'action_order_pizza'
    def run(self,dispatcher,tracker,domain):
        size = tracker.get_slot("size"),
        toppings = tracker.get_slot("toppings")
        dispatcher.utter_message("your pizza size of")
        dispatcher.utter_message(size)
        dispatcher.utter_message("and with toppings")
        dispatcher.utter_message(toppings)
        dispatcher.utter_message('Ordering Pizza is completed! It should be with you soon :)')
                                                                                                                          

my domain.yml file
intents:
    - order_pizza
    - greet
    - size
    - toppings
    - inform
    - affirm
    - goodbye
    - thankyou
    - default

entities:
    - size
    - toppings

slots:
    size:
         type: text
    toppings:
        type: text
    requested_slot:
        type: unfeaturized

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        #- 'Hi, I am here to help.'
    utter_affirm:
        - 'thanks for the details.your order is being processed'
    utter_get_pizza_size:
        - 'What pizza size?'
    utter_get_pizza_toppings:
        - 'What toppings would you like on your pizza?'
    utter_default:
        - 'sorry!i couldnt understand you.please retry'
    utter_thankyou:
        - 'thanks for connecting'
utter_goodbye:
        - 'ok..had a great conversation.would like to serve soon'
actions:
    - utter_greet
    - utter_affirm
    - utter_goodbye
    - utter_thankyou
    - utter_default
    - utter_get_pizza_size
    - utter_get_pizza_toppings
    - action_order_pizza
    - action_fill_size
    - action_fill_toppings
#    - actions.ActionOrderPizza
 

stories.md
## default path
* default
  - utter_default

## affirm path
* affirm
  - utter_affirm

## thankyou path
* thankyou
  - utter_thankyou

## story_path_1
* order_pizza
    - action_order_pizza
    - slot{"requested_slot": "size"}
* inform{"size": "small"}
    - action_order_pizza
    - slot{"requested_slot": "toppings"}
* inform{"toppings": "olives"}
    - action_order_pizza

my nlu.md
## intent:order_pizza
- want to book a pizza
- pizza booking
- book pizza
- pizza
- i want to book an order for pizza

## intent:greet
- hi
- hii
- hello
- hey

## regex:greet
- hey[^\s]*

## intent:default
- bla bla
- do you want to marry me
- i hate you
- i want something else
- can you help me?
- do you love me?
- fuck you

## intent:goodbye
- goodbye
- good bye
- stop
- end
- farewell
- Bye bye
- have a good one

## intent:affirm
- great
- right, thank you
- correct
- great choice
- sounds really good
- yes
- yep
- yeah
- indeed
- thats ok
- ok
- ok fine

## intent:thankyou
- thanks
- thank you
- thank you very much
- nice
- thx alot
- thx
- appreciated
- thankx

## synonym:cheesy
- Cheese
- Cheezy

## intent:size
- small
- medium
- i want [small](size) pizza
- book me a [small](pizza)
- [small](size) pizza
- large
- extra large
- sml
- lrg
- big

## intent: toppings
- olives
- [olives] on top
- cheese
- extra cheese
- cheesy
- book me a pizza with [olives](toppings) on top
- book me a pizza with [corn](toppings)

**Comment by pragya-96** [comment]
my form action is not working.no reply from the end.My bot gets stuck when i ask query regarding pizza booking. can anybody help me with the issue that how to use formaction
my action.py file:
from rasa_core.actions import Action
from rasa_core_sdk.events import SlotSet
from rasa_core.actions.action import Action
from rasa_core_sdk.forms import FormAction
from rasa_core_sdk.forms import EntityFormField
class ActionOrderPizza(Action):
def required_fields():
return [
EntityFormField("size", "size"),
EntityFormField("toppings", "toppings")
]
def name(self):
return 'action_order_pizza'
def run(self,dispatcher,tracker,domain):
size = tracker.get_slot("size"),
toppings = tracker.get_slot("toppings")
dispatcher.utter_message("your pizza size of")
dispatcher.utter_message(size)
dispatcher.utter_message("and with toppings")
dispatcher.utter_message(toppings)
dispatcher.utter_message('Ordering Pizza is completed! It should be with you soon :)')

my domain.yml file
intents:
- order_pizza
- greet
- size
- toppings
- inform
- affirm
- goodbye
- thankyou
- default

entities:
- size
- toppings

slots:
size:
type: text
toppings:
type: text
requested_slot:
type: unfeaturized

templates:
utter_greet:
- 'Hello, how can I help you?'
#- 'Hi, I am here to help.'
utter_affirm:
- 'thanks for the details.your order is being processed'
utter_get_pizza_size:
- 'What pizza size?'
utter_get_pizza_toppings:
- 'What toppings would you like on your pizza?'
utter_default:
- 'sorry!i couldnt understand you.please retry'
utter_thankyou:
- 'thanks for connecting'
utter_goodbye:
- 'ok..had a great conversation.would like to serve soon'
actions:
- utter_greet
- utter_affirm
- utter_goodbye
- utter_thankyou
- utter_default
- utter_get_pizza_size
- utter_get_pizza_toppings
- action_order_pizza
- action_fill_size
- action_fill_toppings

- actions.ActionOrderPizza
stories.md

default path
default
utter_default
affirm path
affirm
utter_affirm
thankyou path
thankyou
utter_thankyou
story_path_1
order_pizza
action_order_pizza
slot{"requested_slot": "size"}
inform{"size": "small"}
action_order_pizza
slot{"requested_slot": "toppings"}
inform{"toppings": "olives"}
action_order_pizza
my nlu.md

intent:order_pizza
want to book a pizza
pizza booking
book pizza
pizza
i want to book an order for pizza
intent:greet
hi
hii
hello
hey
regex:greet
hey[^\s]*
intent:default
bla bla
do you want to marry me
i hate you
i want something else
can you help me?
do you love me?
fuck you
intent:goodbye
goodbye
good bye
stop
end
farewell
Bye bye
have a good one
intent:affirm
great
right, thank you
correct
great choice
sounds really good
yes
yep
yeah
indeed
thats ok
ok
ok fine
intent:thankyou
thanks
thank you
thank you very much
nice
thx alot
thx
appreciated
thankx
synonym:cheesy
Cheese
Cheezy
intent:size
small
medium
i want [small](size) pizza
book me a [small](size)
[small](size) pizza
large
extra large
sml
lrg
big
intent: toppings
olives
[olives](toppings) on top
cheese
extra cheese
cheesy
book me a pizza with [olives](toppings) on top
book me a pizza with [corn](toppings)
