### ISSUE TITLE
Replace pytest-pep8 with pytest-codestyle

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_core_sdk#31]
Pep8 was replaced by pycodestyle.
Hence, `pytest-pep8` is not longer maintained and has to be replaced with `pytest-pycodestyle` (https://pypi.org/project/pytest-pycodestyle/)

Steps:
- [ ] replace dependencies in `requirements.txt` and `setup.py`
- [ ] configure line length etc in `setup.cfg`
- [ ] adapt `.travis`
- [ ] fix new found linter errors

see https://github.com/RasaHQ/rasa_core/pull/1446/files for the first three points

**Comment by tmbo** [comment]
@wochinge are you able to work on this today or should we deprio?

**Comment by wochinge** [comment]
@tmbo It won't work with python2.7 so it's kind of blocked as long as we support python 2.7

**Comment by tmbo** [comment]
Ok makes sense, let's not do it right now then and focus on dropping support for py 2 in core & nlu first.

**Comment by tabergma** [comment]
@wochinge @tmbo I guess we can close this issue as we are not checking against pep8 anymore with the changed done in https://github.com/RasaHQ/rasa_core_sdk/pull/62.

**Comment by wochinge** [comment]
👍
