### ISSUE TITLE
Option to not to add Next Slot Events if event includes `Restarted` or maybe Form Deactivation

### ISSUE THREAD

**Issue by naoko** [RasaHQ/rasa_core_sdk#32]
I was trying to debug [this](https://forum.rasa.com/t/when-followupaction-is-specified-should-all-predicted-event-that-has-not-been-executed-be-reverted/3542/2)

I'm returning `[Restarted(), FollowupAction(name='show_menu')]` from FormAction.
When I issue `Restarted()` I expected that no more utter_ask_SLOT to be uttered but it does.
Not entirely sure if this is a bug or not but by adding code like this in `rasa_core_sdk.forms.FormAction.run` line # 393-ish to below so that when custom 
FormAction issue `Restarted()` maybe other qualififed event, it will not issue `utter_ask_SLOT`
```
next_slot_events = None
if not any(e['event']=='restart' for e in events):
    next_slot_events = self.request_next_slot(dispatcher, temp_tracker,
                                              domain)
```
Maybe you can do fine control by checking Form deactivation then do not add request_next_slot.
What do you think?

**Comment by Ghostvv** [comment]
I answered on the forum. I think the solution would be to override `request_next_slot` method.

**Comment by naoko** [comment]
okay, that's what I end up doing but wasn't sure if it is natural to not to ask next slot when either form is deactivated / things are restarted to give means of force "exit".
But I can also understand that this should be done explicitly.

**Comment by Ghostvv** [comment]
we specifically put asking next slot into separate function for easy overriding
