### ISSUE TITLE
Cannot load actions directory

### ISSUE THREAD

**Issue by alucard001** [RasaHQ/rasa_core_sdk#36]
**Rasa Core SDK version**: Docker rasa_core_sdk:latest

**Python version**: 3.6

**Operating system** (windows, osx, ...): CentOS7

**Issue**:
Assume that I have an `actions` directory with multiple `*.py` actions defined.  If I am running this command:

` docker run -p 5055:5055 --mount type=bind,source=$(pwd)/actions,target=/app/actions rasa/rasa_core_sdk`

It will return 

```
ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
Traceback (most recent call last):
  File "/app/rasa_core_sdk/executor.py", line 144, in register_package
    self._import_submodules(package)
  File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
    package = importlib.import_module(package)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'actions.actions'
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```

It seems that this command did not recognize a dir (or sub-dir within dir) when handling multiple actions.  Please check.

Thank you.

**Comment by akelad** [comment]
Thanks for raising this issue, @EPedrotti  will get back to you about it soon.

**Comment by m-abramovich** [comment]
I've got the same issue. This is not the bug. 

Explaining:
I am here:
`# pwd
/app`
Process looks like this:
`# ps x | grep python | grep -v grep
      1 ?        Ssl    0:00 python -m rasa_core_sdk.endpoint --actions actions.actions`
It was started from this directory:
`# ls -l /proc/1/cwd
lrwxrwxrwx 1 root root 0 Jan 22 19:32 /proc/1/cwd -> /app`
Thus, we expect the directory actions in there. And it really exists:
`# ls -l /app/actions/
total 16
drwx------ 2 root root 16384 Jan 21 14:09 lost+found`
But it has to have two files at minimum: __init__.py and actions.py
None of them are there.

Why? 
Because we need to create them manually (example in here: [4.1 Creating a Custom Action](https://rasa.com/docs/core/docker_walkthrough/#id16))

Solution:
Create themm manually inside the project folder and restart container.

**Comment by m-abramovich** [comment]
But there is still mistake in 4.1

```
mkdir actions
touch __init__.py   <--- not here
touch actions/actions.py
```

Properly:
```
mkdir actions
touch actions/__init__.py   <--- here
touch actions/actions.py
```

**Comment by alucard001** [comment]
> I've got the same issue. This is not the bug.
> 
> Explaining:
> I am here:
> `# pwd /app`
> 
> Process looks like this:
> `# ps x | grep python | grep -v grep 1 ? Ssl 0:00 python -m rasa_core_sdk.endpoint --actions actions.actions`
> 
> It was started from this directory:
> `# ls -l /proc/1/cwd lrwxrwxrwx 1 root root 0 Jan 22 19:32 /proc/1/cwd -> /app`
> 
> Thus, we expect the directory actions in there. And it really exists:
> `# ls -l /app/actions/ total 16 drwx------ 2 root root 16384 Jan 21 14:09 lost+found`
> But it has to have two files at minimum: __ init__.py and actions.py
> None of them are there.
> 
> Why?
> Because we need to create them manually (example in here: [4.1 Creating a Custom Action](https://rasa.com/docs/core/docker_walkthrough/#id16))
> 
> Solution:
> Create them manually inside the project folder and restart container.

Thanks.  It is correct answer.  It works now.  I will close this issue.

**Comment by m-abramovich** [comment]
> Thanks. It is correct answer. It works now. I will close this issue.

You closed the bug but forgot to update documentation.

Reminding: 

- Fix path of __ init__.py in [4.1 Creating a Custom Action](https://rasa.com/docs/core/docker_walkthrough/#creating-a-custom-action)
- Add to [Using Docker Compose](https://rasa.com/docs/core/installation/#id10) preliminaries of creating config and actions prior to starting Compose.

**Comment by akelad** [comment]
@m-abramovich feel free to open a PR to fix these issues

**Comment by m-abramovich** [comment]
@akelad 
PR to documentation? Is it in Git? Where can I find repo?

**Comment by akelad** [comment]
in the rasa_core repo, under `docs` :)
