### ISSUE TITLE
Slots set during a form not useable during validation

### ISSUE THREAD

**Issue by Patrick-DS** [RasaHQ/rasa_core_sdk#43]
**Rasa Core SDK version**: 0.12.1

**Python version**: 3.6.8

**Operating system** : Ubuntu 18.04

**Issue**: From what I've read about conversational UX, it is a good practice when collecting information from the user to offer some kind of confirmation that the bot has properly understood what the user was saying. Right now, with the FormAction in the SDK, one can generate easily a conversation of the following kind, with two slots called "name" and "email" respectively : 

- User : I'd like to register
    - Bot : Ok! What's your name?    <-- produced from utter_ask_name
- User : My name is John
    - Bot : Alright! And what is your e-mail address?  <--- produced from utter_ask_email
- User : My e-mail address is johndoe@domain.com
    - Bot : Alright John! We've sent you an e-mail at johndoe@domain.com for you to create your account.

(The "submit" function can do the e-mail sending and has access to the slots to perform this.)

However, if you wanna do something like this :  

- User : I'd like to register
    - Bot : Ok! What's your name?    <-- produced from utter_ask_name
- User : My name is John
    - Bot : Nice to meet you, John!  <-- produced because name validation was successful via an utter_template in the validate function
    - Bot : May I ask for your e-mail address?  <--- produced from utter_ask_email
- User : My e-mail address is johndoe@domain.com
    - Bot : Alright John! We've sent you an e-mail at johndoe@domain.com for you to create your account.

this is impossible because if you utter a template during the validation process (i.e. by using the tracker passed to the validate function of the form), the "name" slot is not set there yet. The "_validate_if_required" function returns the return value of the "validate" function, which itself returns the list of slots that were set while calling the validate function.

I don't know what exactly would be ideal for the chatbot writer, but I'm guessing that the validate function should only be used to return a dictionary of booleans containing entries of the kind {slot_name : bool} as a function of the currently used slots and the last user message where the slots are extracted from. Then, instead of only be able to utter, there should be a function which allows actions to be taken by the bot (and not just a utterance) with the validated slots values stored in the tracker, including utter_ask_{slotname}. In other words, validate should only validate, and there should be another function allowing you to do stuff after validation.

That's just an idea ; I'm open for other suggestions, but that's what feels most natural to me right now.

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
you can explicitly set validated slots in `utter_template` in your `validate` function:
```
dispatcher.utter_template('utter_nicetomeetyou'),  tracker, name=validated_name)
```

**Comment by Patrick-DS** [comment]
@Ghostvv : That is precisely what doesn't work. I didn't display a MWE above, but even with **tracker.slots, the problem is that during the call of the validation function, the slots are not set yet. (The validation function is the one setting the slots if they are valid, so they can't be in the tracker!) I tried to check if I was out-of-date and if this was fixed in the repo somewhere, I apologize if I couldn't find it. 


I am basing this opinion on the content of version.py and forms.py : 

** version.py 
from __future__ import unicode_literals
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import


__version__ = '0.12.1'

** forms.py
(...)
    def validate(self, dispatcher, tracker, domain):
        # type: (CollectingDispatcher, Tracker, Dict[Text, Any]) -> List[Dict]
        """Validate extracted value of requested slot
            else reject execution of the form action

            Subclass this method to add custom validation and rejection logic
        """
        # extract other slots that were not requested
        # but set by corresponding entity
        slot_values = self.extract_other_slots(dispatcher, tracker, domain)

        # extract requested slot
        slot_to_fill = tracker.get_slot(REQUESTED_SLOT)
        if slot_to_fill:
            slot_values.update(self.extract_requested_slot(dispatcher,
                                                           tracker, domain))
            if not slot_values:
                # reject to execute the form action
                # if some slot was requested but nothing was extracted
                # it will allow other policies to predict another action
                raise ActionExecutionRejection(self.name(),
                                               "Failed to validate slot {0} "
                                               "with action {1}"
                                               "".format(slot_to_fill,
                                                         self.name()))

        # validation succeed, set slots to extracted values
        return [SlotSet(slot, value) for slot, value in slot_values.items()]
(...)

**Comment by Patrick-DS** [comment]
I saw the latest master branch version of forms.py, I think I can work with that. I don't know why I couldn't see it properly last time, maybe I need to update my rasa-core-sdk version... Thanks Ghostvv, this issue can be closed.
