### ISSUE TITLE
In endpoint, could we factor the /health endpoint out of `endpoint_app`?

### ISSUE THREAD

**Issue by m90** [RasaHQ/rasa_core_sdk#6]
I am migrating an existing application running on 0.10 to 0.11. This necessitates the creation of a standalone server for custom action using the newly created SDK.

The application currently serves *multiple* bots, so I need to call `endpoint.endpoint_app` myself (the reasoning being able to use one action package per bot).

I lateron merge these WSGI apps as described here: http://flask.pocoo.org/docs/1.0/patterns/appdispatch/#combining-applications

The issue I am now running into is that each subapp has a dedicated `/<botname>/health` route, when ideally I would like to have my application would expose a single `/health` route at root level (so monitoring does not need to know about my content).

This could be worked around if attaching the health route would be factored out into a standalone function that is then only being called when the module is invoked via `python -m rasa_core_sdk.endpoint`. Consumers (like me) that are using the Python API would need to call this themselves.

Does this make sense? Would you accept a PR that contains the proposed changes?

----

https://github.com/RasaHQ/rasa_core_sdk/blob/acb6ec7d8f6dbcd24ff60453cc93a3cadb0bb936/rasa_core_sdk/endpoint.py#L59-L64

**Comment by tmbo** [comment]
I see what you are trying to achieve, but I am not sure why we would need to remove the endpoints in that case. I mean you do not need to use these health endpoints if you provide your own health endpoint. I did not understand why we need to remove these health endpoints for you to create a combined one, can you explain that a bit?

**Comment by m90** [comment]
I can surely (actually am) create a root health endpoint in addition to the ones that get created by calling `endpoint_app`, but it somehow felt odd to create routes noone is supposed to call, so I thought about how to change it.

Seeing that it wouldn't really affect the existing behavior (and assuming that most consumers that call `endpoint_app` in code will probably not use the `/health` endpoint that it returns - although that's just a guess) I thought it might be worth proposing the change, but leaving it as is would of course also work just fine.

**Comment by tmbo** [comment]
In that case I'd rather like to keep it this way. But feel free to move the appending of the routes of the flask server to a separate function if that helps you combine them in one server.
