### ISSUE TITLE
i think this place(forms.py) has a bug.

### ISSUE THREAD

**Issue by zhangyanbo2007** [RasaHQ/rasa_core_sdk#69]
**Rasa Core SDK version**:0.12.1
**Python version**: 3.6

**Operating system** (windows, osx, ...):ubuntu16.04

**Issue**:
the function "extract_other_slots" in 170 line:
`                for other_slot_mapping in other_slot_mappings:
                    intent = tracker.latest_message.get("intent",
                                                        {}).get("name")
                    # check whether the slot should be filled
                    # by entity with the same name
                    should_fill_slot = (
                            other_slot_mapping["type"] == "from_entity" and
                            other_slot_mapping.get("entity") == slot and
                            self.intent_is_desired(other_slot_mapping,
                                                   tracker)
                    )
                    if should_fill_slot:
                        # list is used to cover the case of list slot type
                        value = list(tracker.get_latest_entity_values(slot))
                        if len(value) == 1:
                            value = value[0]`

i think this place "other_slot_mapping.get("entity") == slot" should be removed,and  this place   "value = list(tracker.get_latest_entity_values(slot))" should be changed as "value = list(tracker.get_latest_entity_values(other_slot_mapping.get("entity")))",because in slot_mapping existing the case of inconsistency in the value of the slot
for example:
in demo-formbot->action.py->slot_mappings: there's a piece of code:
`                "num_people": [self.from_entity(entity="num_people",
                                                intent=["inform",
                                                        "request_restaurant"]),
                               self.from_entity(entity="number")],`
the slot is  "num_people",but the entity is "num_people" and "number",but it means the same.
Looking forward to your reply！
**Content of domain file** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
please format you code snippets in readable format
