### ISSUE TITLE
rasa_core_sdk not supported rasa_core?

### ISSUE THREAD

**Issue by azuredsky** [RasaHQ/rasa_core_sdk#72]
**Rasa Core SDK version**:
0.13.1
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
windows
**Issue**:
Your versions of rasa_core and rasa_core_sdk might not be compatible. You are currently running rasa_core version 0.14.0 and rasa_core_sdk version 0.13.1.
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa_core and rasa_core_sdk.

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
Thanks - sorry for that, we missed to tag a major on the sdk repository. I just did that, if you update your SDK version to `0.14.0` the error should be gone.

**Comment by sarthak-sriw** [comment]
while server is being run :it shows following error:
 UserWarning: Your versions of rasa and rasa_sdk might not be compatible. You are currently running rasa version 0.14.5 and rasa_sdk version 1.6.0.
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa and rasa_sdk.
  f"Your versions of rasa and "

but when I try to update rasa I am getting error:
what to do next?
I am stuck?
![Screenshot (70)](https://user-images.githubusercontent.com/53507883/71556147-a0b71e00-2a5a-11ea-9b23-86c7e42438c3.png)

**Comment by tmbo** [comment]
You should uninstall `rasa_nlu` and `rasa_core` first and then install `rasa`
